### ISSUE TITLE
Bower is needed to build but is not in the npm install file

### ISSUE THREAD

**Issue by whaity** [Defmoves/head#1]
Bower is needed in step to of the install guide. But you are required to insrall this manually. It is not installed along with the npm install that is in step 1.

**Comment by Defmoves** [comment]
True, yet you need to install bower globally to have access to the bower CLI, and I didn't really want to automate any system level modifications. So I listed it as a dependency instead, leaving the decision to the user.

**Comment by Defmoves** [comment]
Woop!
